Creation of image on notification
procrastinot-team/procrastinot pull request #89
Opened 2023-04-19 22:48 UTC by makfazlic

2023-04-20 21:52 UTC, davidbojkovski requested changes
There are a couple of hard-coded strings and number magic, otherwise very nice good and implementation

2023-04-20 21:52 UTC, davidbojkovski commented on app/src/main/java/com/github/mateo762/myapplication/takephoto/TakePhotoActivity.kt
> +            Toast.makeText(this, "Image uploaded successfully", Toast.LENGTH_SHORT).show()
hardcoded text, please add the string to strings.xml and use it from there

2023-04-20 21:52 UTC, davidbojkovski commented on app/src/main/java/com/github/mateo762/myapplication/takephoto/TakePhotoActivity.kt
> +            Toast.makeText(this, "No image data", Toast.LENGTH_SHORT).show()
hardcoded text, please add the string to strings.xml and use it from there

2023-04-21 11:04 UTC, makfazlic commented on app/src/main/res/layout/activity_takephoto.xml
> +<androidx.drawerlayout.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
Done

2023-04-21 11:04 UTC, makfazlic commented on app/src/androidTest/java/com/github/mateo762/myapplication/TakePictureTest.kt
> +        Thread.sleep(2000)
No, because the camera on older emulators takes a while to open, same for the popup

2023-04-21 11:05 UTC, makfazlic commented on app/src/main/java/com/github/mateo762/myapplication/takephoto/TakePhotoActivity.kt
> +        imageView = findViewById(R.id.imageView)
Understood

2023-04-21 11:05 UTC, makfazlic commented on app/src/main/java/com/github/mateo762/myapplication/takephoto/TakePhotoActivity.kt
> +        Log.d("TakePhotoActivity", "User: $currentUser")
It is used when pushing toe image to firebase storage

2023-04-21 11:29 UTC, davidbojkovski approved these changes

2023-04-21 11:33 UTC, merged